### ISSUE TITLE
terraformer-geostore-rtree

### ISSUE THREAD

**Issue by tannerjt** [Esri/terraformer-geostore#10]
Did this change to terraformer-rtree and no longer terraformer-geostore-rtree?  If so, the readme needs updated.

**Comment by jgravois** [comment]
although the github repository name is [`terraformer-geostore-rtree`](https://github.com/Esri/terraformer-geostore-rtree/blob/master/package.json#L2), the npm package name has always been `terraformer-rtree`.  thanks for catching the typo in the README.md, i fixed it in 73dd9c6.
