### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by tadjik1** [Esri/terraformer-geostore#14]
Hi there,
thanks for great module. I've noticed that currently master branch on github has some changes that are not published in npm (`intersects` method, for example). Are you going to release new version any time soon?

**Comment by jgravois** [comment]
just published [`v1.0.5`](https://github.com/Esri/terraformer-geostore/releases/tag/v1.0.5). enjoy!

```bash
$ npm view terraformer-geostore

{ name: 'terraformer-geostore',
  description: 'GeoStore for Terraformer, helps a geo-database toolkit',
  'dist-tags': { latest: '1.0.5' }
```
