### ISSUE TITLE
Can you build a browser version of terraformer-geostore-memory ?

### ISSUE THREAD

**Issue by hoogw** [Esri/terraformer-geostore#19]
I want to use geostore in browser, but failed, 
because no browser version of terraformer-geostore-memory,
available. 

How to build the browser version of it ? can you build it and put on CDN???terraformer-geostore-memory for browser???

**Comment by hoogw** [comment]
The document have wrong code !!!!! take me 3 hours to figure out why

see picture below


               store: new Terraformer.Store.Memory(),
is wrong,


Correct code should be:

               store: new Terraformer.GeoStore.Memory(),

[http://terraformer.io/geostore/][1]
  

[![enter image description here][2]][2]


  [1]: http://terraformer.io/geostore/
  [2]: https://i.stack.imgur.com/tIaSK.png

**Comment by jgravois** [comment]
you can find the source for that documentation page here:

https://github.com/Esri/terraformer/blob/master/docs/geostore.html.md

pull requests welcome.
